name: CI

on:
    push:
      branches:
        - master
    schedule:
    - cron: "0 11 * * *"
    workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  # JOB 1: Test Packages
  # Triggers on: push OR workflow_dispatch
  test:
    name: Test Packages

    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run Chocolatey AU Action
        uses: chocolatey-community/chocolatey-au-action@2.0
        with:
          package-paths: automatic/*
          push: false
          test-install: true
          commit-changes: false

  # JOB 2: Update & Push Packages          
  # Triggers on: schedule OR manual workflow_dispatch (if test succeeded)
  update:
    name: Update & Push Packages
    needs: test

    if: |
      always() && (
        github.event_name == 'schedule' ||
        (github.event_name == 'workflow_dispatch' && needs.test.result == 'success')
      )

    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run Chocolatey AU Action
        uses: chocolatey-community/chocolatey-au-action@2.0
        with:
          package-paths: automatic/*
          push: true
          api-key: ${{ secrets.CHOCO_TOKEN }}
          test-install: true
          commit-changes: true
        