name: CI

on:
    push:
      branches:
        - master
    schedule:
    - cron: "0 11 * * *"
    workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  test:
    name: Test Packages

    # Runs on git pushes OR manual triggers
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
          Install-Module -Name powerhtml -Scope CurrentUser -Force

      - name: Run Chocolatey AU Action
        uses: chocolatey-community/chocolatey-au-action@2.0
        with:
          package-paths: automatic/*
          push: false
          test-install: true
          commit-changes: false
  update:
    name: Update & Push Packages

    # Runs on schedule (cron) OR manual triggers
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'

    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
          Install-Module -Name powerhtml -Scope CurrentUser -Force

      - name: Run Chocolatey AU Action
        uses: chocolatey-community/chocolatey-au-action@2.0
        with:
          package-paths: automatic/*
          push: true
          api-key: ${{ secrets.CHOCO_TOKEN }}
          test-install: true
          commit-changes: true
        