name: test-packages

on:
    push:
      branches:
        - master
    workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
          Install-Module -Name powerhtml -Scope CurrentUser -Force

      - name: Run Chocolatey AU Action
        uses: chocolatey-community/chocolatey-au-action@2.0
        with:
          package-paths: automatic/*

          push: false
          test-install: true
          commit-changes: false
